# Generated by Django 5.2.12 on 2026-03-06 13:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("machine_id", models.CharField(max_length=50, unique=True)),
                ("machine_name", models.CharField(max_length=100)),
                (
                    "machine_type",
                    models.CharField(
                        choices=[
                            ("HMC", "Horizontal Machining Center"),
                            ("VMC", "Vertical Machining Center"),
                            ("CNC", "CNC Machine"),
                            ("LATHE", "CNC Lathe"),
                        ],
                        default="HMC",
                        max_length=20,
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "model_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "spindle_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("max_rpm", models.IntegerField(blank=True, null=True)),
                ("max_tools", models.IntegerField(default=60)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("MAINTENANCE", "Maintenance"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "machines",
                "ordering": ["machine_id"],
            },
        ),
        migrations.CreateModel(
            name="SKUCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefix", models.CharField(max_length=10, unique=True)),
                ("current_value", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "sku_counters",
            },
        ),
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("component_name", models.CharField(max_length=150)),
                (
                    "part_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("material", models.CharField(blank=True, default="", max_length=100)),
                ("customer", models.CharField(blank=True, default="", max_length=200)),
                (
                    "drawing_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("operation", models.CharField(blank=True, default="", max_length=100)),
                (
                    "cycle_time_minutes",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("status", models.CharField(default="ACTIVE", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="tools.machine",
                    ),
                ),
            ],
            options={
                "db_table": "components",
                "ordering": ["component_name"],
                "unique_together": {("machine", "component_name", "operation")},
            },
        ),
        migrations.CreateModel(
            name="MachineTools",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("Tooling", "Tooling"),
                            ("Gauges", "Gauges"),
                            ("Fixture", "Fixture"),
                        ],
                        db_index=True,
                        default="Tooling",
                        max_length=20,
                    ),
                ),
                ("tool_number", models.CharField(max_length=10)),
                ("tool_name", models.CharField(max_length=150)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("END_MILL", "End Mill"),
                            ("FACE_MILL", "Face Mill"),
                            ("DRILL", "Drill"),
                            ("TAP", "Tap"),
                            ("REAMER", "Reamer"),
                            ("BORING_BAR", "Boring Bar"),
                            ("MILLING_CUTTER", "Milling Cutter"),
                            ("U_DRILL", "U Drill"),
                            ("SPECIAL", "Special"),
                            ("OTHER", "Other"),
                        ],
                        default="END_MILL",
                        max_length=20,
                    ),
                ),
                (
                    "diameter",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "corner_radius",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "insert_used",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "initial_life",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "current_life",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "life_used",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("supplier", models.CharField(blank=True, default="", max_length=150)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("TRIAL_PENDING", "Trial Pending"),
                            ("ACTIVE", "Active"),
                            ("TRIAL", "Trial"),
                            ("WORN_OUT", "Worn Out"),
                            ("INACTIVE", "Inactive"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("trial_required", models.BooleanField(default=False)),
                ("remarks", models.TextField(blank=True, default="")),
                (
                    "drawing_file",
                    models.FileField(blank=True, null=True, upload_to="tool_drawings/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "component",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tools",
                        to="tools.component",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tools",
                        to="tools.machine",
                    ),
                ),
            ],
            options={
                "db_table": "machine_tools",
                "ordering": ["machine", "tool_number"],
            },
        ),
        migrations.CreateModel(
            name="Master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "master_type",
                    models.CharField(
                        choices=[
                            ("PULLSTUD", "Pull Stud"),
                            ("ADAPTOR", "Adaptor"),
                            ("COLLET", "Collet"),
                            ("CUTTING_TOOL", "Cutting Tool"),
                            ("INSERT", "Insert"),
                            ("SUPPLIER", "Supplier"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("specifications", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "masters",
                "ordering": ["master_type", "name"],
                "indexes": [
                    models.Index(
                        fields=["master_type", "status"],
                        name="masters_master__0fccc7_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PlanningData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("production_qty", models.IntegerField(default=0)),
                (
                    "tool_life_per_component",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("tools_required", models.IntegerField(default=0)),
                ("inserts_required", models.IntegerField(default=0)),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("month", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planning_data",
                        to="tools.component",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planning_data",
                        to="tools.machine",
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planning_data",
                        to="tools.machinetools",
                    ),
                ),
            ],
            options={
                "db_table": "planning_data",
                "ordering": ["-month"],
            },
        ),
        migrations.CreateModel(
            name="ToolBOM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bom_type",
                    models.CharField(
                        choices=[
                            ("PULLSTUD", "Pull Stud"),
                            ("ADAPTOR", "Adaptor"),
                            ("NUT_COLLET", "Nut / Collet"),
                            ("CUTTING_TOOL", "Cutting Tool"),
                            ("INSERT", "Insert"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "drawing_file",
                    models.FileField(
                        blank=True, null=True, upload_to="tool_bom_drawings/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "master_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bom_items",
                        to="tools.master",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"master_type": "SUPPLIER"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bom_suppliers",
                        to="tools.master",
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom_items",
                        to="tools.machinetools",
                    ),
                ),
            ],
            options={
                "db_table": "tool_bom",
                "ordering": ["tool", "bom_type"],
            },
        ),
        migrations.CreateModel(
            name="ToolBOMDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cutting_tool_type",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("shape_data", models.JSONField(blank=True, default=dict)),
                ("life_data", models.JSONField(blank=True, default=dict)),
                ("other_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bom",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detail",
                        to="tools.toolbom",
                    ),
                ),
            ],
            options={
                "db_table": "tool_bom_details",
            },
        ),
        migrations.CreateModel(
            name="ToolLife",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("FINALIZED", "Finalized")],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("finalized_date", models.DateTimeField(blank=True, null=True)),
                (
                    "finalized_by",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "life",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "cut_time",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "life_per_corner",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "life_in_meters",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tool",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="life_data",
                        to="tools.machinetools",
                    ),
                ),
            ],
            options={
                "db_table": "tool_life",
            },
        ),
        migrations.CreateModel(
            name="ToolMasterImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(blank=True, default="", max_length=255)),
                ("total_rows", models.IntegerField(default=0)),
                ("success_count", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("errors", models.JSONField(blank=True, default=list)),
                ("data", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "imported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tool_master_imports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ToolOtherDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("FINALIZED", "Finalized")],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("finalized_date", models.DateTimeField(blank=True, null=True)),
                (
                    "finalized_by",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("tool_used_machine_date", models.DateField(blank=True, null=True)),
                ("supplier", models.CharField(blank=True, default="", max_length=150)),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("trial_by", models.CharField(blank=True, default="", max_length=100)),
                (
                    "approved_by",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("correction_remark", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tool",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="other_details",
                        to="tools.machinetools",
                    ),
                ),
            ],
            options={
                "db_table": "tool_other_details",
            },
        ),
        migrations.CreateModel(
            name="ToolShape",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("FINALIZED", "Finalized")],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("finalized_date", models.DateTimeField(blank=True, null=True)),
                (
                    "finalized_by",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "tool_system_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "nom_d",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("id_code", models.CharField(blank=True, default="", max_length=100)),
                (
                    "tool_identity_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "length",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "leng_co",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("no", models.IntegerField(blank=True, null=True)),
                (
                    "insert_used",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "corner_r",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("no_of_corners", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tool",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shape_data",
                        to="tools.machinetools",
                    ),
                ),
            ],
            options={
                "db_table": "tool_shape",
            },
        ),
        migrations.CreateModel(
            name="ToolTrialMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("machine_name", models.CharField(max_length=100)),
                ("component_name", models.CharField(max_length=150)),
                ("tool_number", models.CharField(max_length=20)),
                ("tool_name", models.CharField(max_length=200)),
                ("operation", models.CharField(blank=True, default="", max_length=200)),
                ("customer", models.CharField(blank=True, default="", max_length=200)),
                ("part_name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "part_material",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "existing_manufacturer",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "existing_insert_code",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("existing_cutting_edges", models.IntegerField(blank=True, null=True)),
                (
                    "existing_cutting_speed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "existing_feed",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "existing_coolant",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DRY", "Dry"),
                            ("FLOOD", "Flood"),
                            ("MIST", "Mist"),
                            ("MQL", "MQL"),
                            ("THROUGH_TOOL", "Through Tool"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("existing_tool_life", models.IntegerField(blank=True, null=True)),
                (
                    "existing_cutting_time",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "new_manufacturer",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "new_insert_code",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("new_cutting_edges", models.IntegerField(blank=True, null=True)),
                (
                    "new_cutting_speed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "new_feed",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "new_coolant",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DRY", "Dry"),
                            ("FLOOD", "Flood"),
                            ("MIST", "Mist"),
                            ("MQL", "MQL"),
                            ("THROUGH_TOOL", "Through Tool"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("new_tool_life", models.IntegerField(blank=True, null=True)),
                (
                    "new_cutting_time",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("spindle_speed", models.IntegerField(blank=True, null=True)),
                (
                    "feed_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "depth_of_cut",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "cutting_speed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("target_quantity", models.IntegerField(blank=True, null=True)),
                ("test_pieces_qty", models.IntegerField(blank=True, null=True)),
                (
                    "surface_finish_ra",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                ("tool_life_achieved", models.IntegerField(blank=True, null=True)),
                (
                    "existing_cost_per_component",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "new_cost_per_component",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "savings_per_component",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "monthly_savings",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "trial_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PASS", "Pass"),
                            ("FAIL", "Fail"),
                            ("CONDITIONAL", "Conditional Pass"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("trial_date", models.DateField(blank=True, null=True)),
                (
                    "conducted_by",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "approved_by",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True, default="")),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trial_masters",
                        to="tools.machinetools",
                    ),
                ),
            ],
            options={
                "db_table": "tool_trial_master",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ToolTrialInsert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insert_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("iso_code", models.CharField(blank=True, default="", max_length=50)),
                ("grade", models.CharField(blank=True, default="", max_length=50)),
                ("coating", models.CharField(blank=True, default="", max_length=100)),
                ("no_of_inserts", models.IntegerField(blank=True, null=True)),
                ("no_of_corners", models.IntegerField(blank=True, null=True)),
                ("insert_life", models.IntegerField(blank=True, null=True)),
                ("life_per_edge", models.IntegerField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trial",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insert_detail",
                        to="tools.tooltrialmaster",
                    ),
                ),
            ],
            options={
                "db_table": "tool_trial_insert",
            },
        ),
        migrations.CreateModel(
            name="ToolTrialCuttingTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tool_type",
                    models.CharField(
                        choices=[
                            ("DRILL", "Drill"),
                            ("ENDMILL", "Endmill"),
                            ("BORING_BAR", "Boring Bar"),
                            ("SPECIAL", "Special"),
                            ("REAMER", "Reamer"),
                            ("TAP", "Tap"),
                            ("MILLING_CUTTER", "Milling Cutter"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "diameter",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("flutes", models.IntegerField(blank=True, null=True)),
                (
                    "oal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("material", models.CharField(blank=True, default="", max_length=100)),
                ("coating", models.CharField(blank=True, default="", max_length=100)),
                ("make", models.CharField(blank=True, default="", max_length=100)),
                ("tool_code", models.CharField(blank=True, default="", max_length=100)),
                ("remarks", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cutting_tools",
                        to="tools.tooltrialmaster",
                    ),
                ),
            ],
            options={
                "db_table": "tool_trial_cutting_tools",
            },
        ),
        migrations.CreateModel(
            name="ToolTrialAdaptor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "adaptor_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("interface", models.CharField(blank=True, default="", max_length=100)),
                (
                    "length",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("make", models.CharField(blank=True, default="", max_length=100)),
                (
                    "coolant_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("remarks", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trial",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adaptor",
                        to="tools.tooltrialmaster",
                    ),
                ),
            ],
            options={
                "db_table": "tool_trial_adaptor",
            },
        ),
        migrations.CreateModel(
            name="ToolTrialPullstud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pullstud_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "thread_size",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "length",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("make", models.CharField(blank=True, default="", max_length=100)),
                ("material", models.CharField(blank=True, default="", max_length=50)),
                ("coolant_through", models.BooleanField(default=False)),
                ("remarks", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trial",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pullstud",
                        to="tools.tooltrialmaster",
                    ),
                ),
            ],
            options={
                "db_table": "tool_trial_pullstud",
            },
        ),
        migrations.AddIndex(
            model_name="machinetools",
            index=models.Index(
                fields=["machine", "status"], name="machine_too_machine_010edc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="machinetools",
            index=models.Index(
                fields=["machine", "asset_type", "status"],
                name="machine_too_machine_5cb498_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="machinetools",
            unique_together={("machine", "tool_number")},
        ),
        migrations.AlterUniqueTogether(
            name="toolbom",
            unique_together={("tool", "bom_type")},
        ),
        migrations.AddIndex(
            model_name="tooltrialmaster",
            index=models.Index(
                fields=["tool", "status"], name="tool_trial__tool_id_a23680_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tooltrialmaster",
            index=models.Index(
                fields=["status", "created_at"], name="tool_trial__status_a9527a_idx"
            ),
        ),
    ]
