# Generated by Django 5.2.12 on 2026-03-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="machinetools",
            name="pocket_number",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="toolbom",
            name="sku",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="toolbomdetail",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="toolbomdetail",
            name="parameter_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="machinetools",
            name="category",
            field=models.CharField(
                choices=[
                    ("MILLING_CUTTER", "Milling Cutter"),
                    ("DRILL", "Drill"),
                    ("ENDMILL", "Endmill"),
                    ("TAP", "Tap"),
                    ("THREADMILL", "Threadmill"),
                    ("BORING_BAR", "Boring Bar"),
                    ("REAMERS", "Reamers"),
                    ("SPECIAL_DRILL", "Special Drill"),
                    ("SPECIAL_TOOL", "Special Tool"),
                    ("OTHER", "Other"),
                ],
                default="MILLING_CUTTER",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="skucounter",
            name="prefix",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="toolbom",
            name="bom_type",
            field=models.CharField(
                choices=[
                    ("PULLSTUD", "Pull Stud"),
                    ("ADAPTOR", "Adaptor"),
                    ("TOOL", "Tool"),
                    ("INSERT", "Insert"),
                    ("CARTRIDGE", "Cartridge"),
                    ("MBU", "MBU"),
                    ("BORING_HEAD", "Boring Head / Boring Bar"),
                    ("NUT_COLLET", "Nut / Collet"),
                    ("CUTTING_TOOL", "Cutting Tool"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="toolbomdetail",
            name="cutting_tool_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DRILL", "Drill"),
                    ("ENDMILL", "Endmill"),
                    ("TAP", "Tap"),
                    ("THREADMILL", "Threadmill"),
                    ("MILLING_CUTTER", "Milling Cutter"),
                    ("SPECIAL_TOOL", "Special Tool"),
                ],
                default="",
                max_length=30,
            ),
        ),
    ]
