# Generated by Django 5.2.12 on 2026-03-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0002_machinetools_pocket_number_toolbom_sku_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toolbom",
            name="bom_type",
            field=models.CharField(
                choices=[
                    ("PULLSTUD", "Pull Stud"),
                    ("ADAPTOR", "Adaptor"),
                    ("TOOL", "Tool"),
                    ("INSERT", "Insert"),
                    ("CARTRIDGE", "Cartridge"),
                    ("MBU", "MBU"),
                    ("BORING_HEAD", "Boring Head / Boring Bar"),
                    ("COLLET", "Collet"),
                    ("INSERT_SCREW", "Insert Screw"),
                    ("SCREW", "Screw"),
                    ("MIDDLE_EXTENSION", "Middle Extension"),
                    ("NUT_COLLET", "Nut / Collet"),
                    ("CUTTING_TOOL", "Cutting Tool"),
                ],
                max_length=20,
            ),
        ),
    ]
