# Generated by Django 5.2.12 on 2026-03-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0003_add_new_bom_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="toolbom",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, help_text="Quantity of this subassembly"
            ),
        ),
    ]
